version: 0.2

env:
  variables:
    BUNDLER_VERSION: 2.0

phases:
    build:
      commands:
        - gem update --system
        - gem install bundler -v '2.0'
        - bundle install
        - bundle exec jekyll build
artifacts:
    base-directory: _site
    files:
      - '**/*'
cache:
    paths: []
