name: Jekyll site CI

on:
  push:
    branches: [ "master", "tjbenator-github-actions" ]
  pull_request:
    branches: [ "master", "tjbenator-github-actions" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: binarypenguin/binarypenguin-net:latest
